### ISSUE TITLE
Feature Request: ABAP Syntax

### ISSUE THREAD

**Issue by JorisM** [igorw/trashbin#2]
Hello Igor
Ich bruche zum schaffe amigs din Pastebin, 1a sach.
Frage: isches möglich d sprach ABAP hinzuäfuägä? 
Wär super.

Joris
PS: isch das de richtig Ort für en feature request?

**Comment by igorw** [comment]
[SHJS](http://shjs.sourceforge.net/) (JavaScript highlighting library) understützt vo sich us kei ABAP ([understützti sprache](http://shjs.sourceforge.net/doc/documentation.html#classes)).

Falls du irgendwo en ABAP highlighter for SHJS oder GNU Source-Highlight (es git en converter vo GNU Source-Highlight zu SHJS) findisch, channis hinzuefüege.

Oder chasch natürli probiere sälber ABAP syntax z implementiere. Sött eigentlich nöd so schwirig si. Luegsch mal di existierende sprachene a: http://shjs.sourceforge.net/lang/ und d css klassene wod chasch verwende (sh_keyword, sh_type, sh_string usw): http://shjs.sourceforge.net/sh_style.css plus SHJS doku: http://shjs.sourceforge.net/doc/documentation.html

**Comment by JorisM** [comment]
ok thanks, ich wirds mal checke sobaldi chli ziit ha;) merci!
